quarkus:
  mongodb:
    database: prono
  http:
    port: 8081
    host: 192.168.0.100
    cors: true
  swagger-ui:
    always-include: true
  oidc:
    client-id: prono-back
    application-type: SERVICE
    
# Production profile
"%prod":
  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
    oidc:
      auth-server-url: http://192.168.0.100:8080/realms/prono
    
# Development profile
"%dev":
  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
      devservices: 
        enabled: false
    oidc:
      auth-server-url: http://192.168.0.100:8080/realms/prono